
ALL_FILES = $(shell git ls-files regressions)
all: $(ALL_FILES)
	git status regressions

define sync-stats
$1: $(subst regressions/,MOM6-examples/,$1)
	cp $$< $$@
	git status --porcelain $$@
endef
$(foreach file,$(ALL_FILES),$(eval $(call sync-stats,$(file))))
